Build for both macOS-11 and macOS-12

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,19 @@ name: Setup
 on: [push]
 
 jobs:
-  build:
+  macOS-11-build:
+    runs-on: macOS-11
+    steps:
+    - uses: actions/checkout@v2
+    - name: brew install
+      run: brew bundle
+    - name: bundle install & serverkit apply
+      run: ./serverkit-setup.bash
+    - name: serverkit check
+      run: |
+        # just check, ignore exit status
+        bundle exec serverkit check serverkit.yml.erb --variables=serverkit-variables.yml || exit 0
+  macOS-12-build:
     runs-on: macOS-12
     steps:
     - uses: actions/checkout@v2
